# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'GXMessagesTableViewSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings! #抑制所有的警告!
  # Pods for GXMessagesTableViewSample

pod 'GXCategories'
pod 'GXRefresh'
pod 'Reusable'

end
